//! GENERATED from `data/gitleaks/gitleaks.toml` (gitleaks v8.30.1, MIT).
//! Do not edit. Regenerate with
//! `CERBERUST_REGENERATE_GITLEAKS=1 cargo test --test gitleaks_rules`.
//!
//! 200 rules included; 22 excluded (see [`EXCLUDED`]).

use super::gitleaks::{Allowlist, Rule};

/// The ported gitleaks rules, in upstream order.
pub(crate) const RULES: &[Rule] = &[
    Rule {
        id: r"1password-secret-key",
        ty: r"1PASSWORD_SECRET_KEY",
        regex: r"(?-u:\b)A3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"a3-",
        ],
        gated: true,
        entropy: 3.8,
        allowlists: &[],
    },
    Rule {
        id: r"1password-service-account-token",
        ty: r"1PASSWORD_SERVICE_ACCOUNT_TOKEN",
        regex: r"ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}",
        secret_group: 0,
        keywords: &[
            r"ops_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"adafruit-api-key",
        ty: r"ADAFRUIT_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:adafruit)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9_-]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"adafruit",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"adobe-client-secret",
        ty: r"ADOBE_CLIENT_SECRET",
        regex: r#"(?-u:\b)(p8e-(?i)[a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"p8e-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"age-secret-key",
        ty: r"AGE_SECRET_KEY",
        regex: r"AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}",
        secret_group: 0,
        keywords: &[
            r"age-secret-key-1",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"airtable-api-key",
        ty: r"AIRTABLE_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:airtable)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{17})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"airtable",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"airtable-personnal-access-token",
        ty: r"AIRTABLE_PERSONNAL_ACCESS_TOKEN",
        regex: r"(?-u:\b)(pat[[:alnum:]]{14}\.[a-f0-9]{64})(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"airtable",
        ],
        gated: false,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"algolia-api-key",
        ty: r"ALGOLIA_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:algolia)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"algolia",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"alibaba-access-key-id",
        ty: r"ALIBABA_ACCESS_KEY_ID",
        regex: r#"(?-u:\b)(LTAI(?i)[a-z0-9]{20})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"ltai",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"alibaba-secret-key",
        ty: r"ALIBABA_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:alibaba)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{30})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"alibaba",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"anthropic-admin-api-key",
        ty: r"ANTHROPIC_ADMIN_API_KEY",
        regex: r#"(?-u:\b)(sk-ant-admin01-[a-zA-Z0-9_\-]{93}AA)(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sk-ant-admin01",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"anthropic-api-key",
        ty: r"ANTHROPIC_API_KEY",
        regex: r#"(?-u:\b)(sk-ant-api03-[a-zA-Z0-9_\-]{93}AA)(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sk-ant-api03",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"artifactory-api-key",
        ty: r"ARTIFACTORY_API_KEY",
        regex: r"(?-u:\b)AKCp[A-Za-z0-9]{69}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"akcp",
        ],
        gated: true,
        entropy: 4.5,
        allowlists: &[],
    },
    Rule {
        id: r"artifactory-reference-token",
        ty: r"ARTIFACTORY_REFERENCE_TOKEN",
        regex: r"(?-u:\b)cmVmd[A-Za-z0-9]{59}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"cmvmd",
        ],
        gated: true,
        entropy: 4.5,
        allowlists: &[],
    },
    Rule {
        id: r"asana-client-secret",
        ty: r"ASANA_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:asana)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"asana",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"atlassian-api-token",
        ty: r"ATLASSIAN_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:(?-i:ATLASSIAN|[Aa]tlassian)|(?-i:CONFLUENCE|[Cc]onfluence)|(?-i:JIRA|[Jj]ira))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)|(?-u:\b)(ATATT3[A-Za-z0-9_\-=]{186})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"atlassian",
            r"confluence",
            r"jira",
            r"atatt3",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[],
    },
    Rule {
        id: r"authress-service-client-access-key",
        ty: r"AUTHRESS_SERVICE_CLIENT_ACCESS_KEY",
        regex: r#"(?-u:\b)((?:sc|ext|scauth|authress)_(?i)[a-z0-9]{5,30}\.[a-z0-9]{4,6}\.(?-i:acc)[_-][a-z0-9-]{10,32}\.[a-z0-9+/_=-]{30,120})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sc_",
            r"ext_",
            r"scauth_",
            r"authress_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"aws-access-token",
        ty: r"AWS_ACCESS_TOKEN",
        regex: r"(?-u:\b)((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"a3t",
            r"akia",
            r"asia",
            r"abia",
            r"acca",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: false,
                regexes: &[
                    r".+EXAMPLE$",
                ],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"aws-amazon-bedrock-api-key-long-lived",
        ty: r"AWS_AMAZON_BEDROCK_API_KEY_LONG_LIVED",
        regex: r#"(?-u:\b)(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"absk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"aws-amazon-bedrock-api-key-short-lived",
        ty: r"AWS_AMAZON_BEDROCK_API_KEY_SHORT_LIVED",
        regex: r"bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t",
        secret_group: 0,
        keywords: &[
            r"bedrock-api-key-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"azure-ad-client-secret",
        ty: r"AZURE_AD_CLIENT_SECRET",
        regex: r#"(?:^|[\\'"\x60\t\n\f\r >=:(,)])([a-zA-Z0-9_~.]{3}[0-9]Q~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\'"\x60\t\n\f\r <),])"#,
        secret_group: 0,
        keywords: &[
            r"q~",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"beamer-api-token",
        ty: r"BEAMER_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:beamer)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(b_[a-z0-9=_\-]{44})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"beamer",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"bitbucket-client-secret",
        ty: r"BITBUCKET_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:bitbucket)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"bitbucket",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"bittrex-access-key",
        ty: r"BITTREX_ACCESS_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:bittrex)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"bittrex",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"bittrex-secret-key",
        ty: r"BITTREX_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:bittrex)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"bittrex",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"cisco-meraki-api-key",
        ty: r"CISCO_MERAKI_API_KEY",
        regex: r#"[0-9A-Za-z_.-]{0,50}?(?i:[0-9A-Za-z_.-]{0,50}?(?:(?-i:[Mm]eraki|MERAKI))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9a-f]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"meraki",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"clickhouse-cloud-api-secret-key",
        ty: r"CLICKHOUSE_CLOUD_API_SECRET_KEY",
        regex: r"(?-u:\b)(4b1d[A-Za-z0-9]{38})(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"4b1d",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"clojars-api-token",
        ty: r"CLOJARS_API_TOKEN",
        regex: r"(?i)CLOJARS_[a-z0-9]{60}",
        secret_group: 0,
        keywords: &[
            r"clojars_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"cloudflare-api-key",
        ty: r"CLOUDFLARE_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:cloudflare)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9_-]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"cloudflare",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"cloudflare-global-api-key",
        ty: r"CLOUDFLARE_GLOBAL_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:cloudflare)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{37})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"cloudflare",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"cloudflare-origin-ca-key",
        ty: r"CLOUDFLARE_ORIGIN_CA_KEY",
        regex: r#"(?-u:\b)(v1\.0-[a-f0-9]{24}-[a-f0-9]{146})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"cloudflare",
            r"v1.0-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"codecov-access-token",
        ty: r"CODECOV_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:codecov)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"codecov",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"cohere-api-token",
        ty: r"COHERE_API_TOKEN",
        regex: r#"[0-9A-Za-z_.-]{0,50}?(?i:[0-9A-Za-z_.-]{0,50}?(?:cohere|CO_API_KEY)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-zA-Z0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"cohere",
            r"co_api_key",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"coinbase-access-token",
        ty: r"COINBASE_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:coinbase)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9_-]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"coinbase",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"confluent-access-token",
        ty: r"CONFLUENT_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:confluent)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"confluent",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"confluent-secret-key",
        ty: r"CONFLUENT_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:confluent)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"confluent",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"contentful-delivery-api-token",
        ty: r"CONTENTFUL_DELIVERY_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:contentful)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{43})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"contentful",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"curl-auth-header",
        ty: r"CURL_AUTH_HEADER",
        regex: r#"(?-u:\b)curl(?-u:\b)(?:.*?|.*?(?:[\r\n]{1,2}.*?){1,5})[ \t\n\r](?:-H|--header)(?:=|[ \t]{0,5})(?:"(?i)(?:Authorization:[ \t]{0,5}(?:Basic[ \t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \t]([0-9A-Za-z_=~@.+/-]{8,})|([0-9A-Za-z_=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \t]{0,5}([0-9A-Za-z_=~@.+/-]{8,}))"|'(?i)(?:Authorization:[ \t]{0,5}(?:Basic[ \t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \t]([0-9A-Za-z_=~@.+/-]{8,})|([0-9A-Za-z_=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \t]{0,5}([0-9A-Za-z_=~@.+/-]{8,}))')(?:(?-u:\B)|[\t\n\f\r ]|\z)"#,
        secret_group: 0,
        keywords: &[
            r"curl",
        ],
        gated: true,
        entropy: 2.75,
        allowlists: &[],
    },
    Rule {
        id: r"curl-auth-user",
        ty: r"CURL_AUTH_USER",
        regex: r#"(?-u:\b)curl(?-u:\b)(?:.*|.*(?:[\r\n]{1,2}.*){1,5})[ \t\n\r](?:-u|--user)(?:=|[ \t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|'([^:']{3,}:[^']{3,})'|((?:"[^"]{3,}"|'[^']{3,}'|[0-9A-Za-z_$@.-]+):(?:"[^"]{3,}"|'[^']{3,}'|[0-9A-Za-z_${}@.-]+)))(?:[\t\n\f\r ]|\z)"#,
        secret_group: 0,
        keywords: &[
            r"curl",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: false,
                regexes: &[
                    r"[^:]+:(?:change(?:it|me)|pass(?:word)?|pwd|test|token|\*+|x+)",
                    r#"['"]?<[^>]+>['"]?:['"]?<[^>]+>|<[^:]+:[^>]+>['"]?"#,
                    r"[^:]+:\[[^]]+]",
                    r#"['"]?[^:]+['"]?:['"]?\$(?:[0-9]|[0-9A-Za-z_]+|\{(?:[0-9]|[0-9A-Za-z_]+)})['"]?"#,
                    r"\$\([^)]+\):\$\([^)]+\)",
                    r#"['"]?\$?\{\{[^}]+}}['"]?:['"]?\$?\{\{[^}]+}}['"]?"#,
                ],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"databricks-api-token",
        ty: r"DATABRICKS_API_TOKEN",
        regex: r#"(?-u:\b)(dapi[a-f0-9]{32}(?:-[0-9])?)(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dapi",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"datadog-access-token",
        ty: r"DATADOG_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:datadog)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"datadog",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"defined-networking-api-token",
        ty: r"DEFINED_NETWORKING_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:dnkey)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(dnkey-[a-z0-9=_\-]{26}-[a-z0-9=_\-]{52})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dnkey",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"digitalocean-access-token",
        ty: r"DIGITALOCEAN_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(doo_v1_[a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"doo_v1_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"digitalocean-pat",
        ty: r"DIGITALOCEAN_PAT",
        regex: r#"(?-u:\b)(dop_v1_[a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dop_v1_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"digitalocean-refresh-token",
        ty: r"DIGITALOCEAN_REFRESH_TOKEN",
        regex: r#"(?i)(?-u:\b)(dor_v1_[a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dor_v1_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"discord-api-token",
        ty: r"DISCORD_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:discord)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"discord",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"discord-client-secret",
        ty: r"DISCORD_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:discord)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"discord",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"doppler-api-token",
        ty: r"DOPPLER_API_TOKEN",
        regex: r"dp\.pt\.(?i)[a-z0-9]{43}",
        secret_group: 0,
        keywords: &[
            r"dp.pt.",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"droneci-access-token",
        ty: r"DRONECI_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:droneci)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"droneci",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"dropbox-api-token",
        ty: r"DROPBOX_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:dropbox)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{15})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dropbox",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"dropbox-long-lived-api-token",
        ty: r"DROPBOX_LONG_LIVED_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:dropbox)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\-_=]{43})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dropbox",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"dropbox-short-lived-api-token",
        ty: r"DROPBOX_SHORT_LIVED_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:dropbox)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(sl\.[a-z0-9\-=_]{135})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"dropbox",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"duffel-api-token",
        ty: r"DUFFEL_API_TOKEN",
        regex: r"duffel_(?:test|live)_(?i)[a-z0-9_\-=]{43}",
        secret_group: 0,
        keywords: &[
            r"duffel_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"dynatrace-api-token",
        ty: r"DYNATRACE_API_TOKEN",
        regex: r"dt0c01\.(?i)[a-z0-9]{24}\.[a-z0-9]{64}",
        secret_group: 0,
        keywords: &[
            r"dt0c01.",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"easypost-api-token",
        ty: r"EASYPOST_API_TOKEN",
        regex: r"(?-u:\b)EZAK(?i)[a-z0-9]{54}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"ezak",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"easypost-test-api-token",
        ty: r"EASYPOST_TEST_API_TOKEN",
        regex: r"(?-u:\b)EZTK(?i)[a-z0-9]{54}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"eztk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"etsy-access-token",
        ty: r"ETSY_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:(?-i:ETSY|[Ee]tsy))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{24})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"etsy",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"facebook-access-token",
        ty: r"FACEBOOK_ACCESS_TOKEN",
        regex: r#"(?i)(?-u:\b)([0-9]{15,16}(\||%)[0-9a-z\-_]{27,40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"facebook",
        ],
        gated: false,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"facebook-page-access-token",
        ty: r"FACEBOOK_PAGE_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(EAA[MC](?i)[a-z0-9]{100,})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"eaam",
            r"eaac",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"facebook-secret",
        ty: r"FACEBOOK_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:facebook)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"facebook",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"fastly-api-token",
        ty: r"FASTLY_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:fastly)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"fastly",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"finicity-api-token",
        ty: r"FINICITY_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:finicity)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"finicity",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"finicity-client-secret",
        ty: r"FINICITY_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:finicity)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{20})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"finicity",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"finnhub-access-token",
        ty: r"FINNHUB_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:finnhub)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{20})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"finnhub",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"flickr-access-token",
        ty: r"FLICKR_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:flickr)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"flickr",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"flutterwave-encryption-key",
        ty: r"FLUTTERWAVE_ENCRYPTION_KEY",
        regex: r"FLWSECK_TEST-(?i)[a-h0-9]{12}",
        secret_group: 0,
        keywords: &[
            r"flwseck_test",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"flutterwave-secret-key",
        ty: r"FLUTTERWAVE_SECRET_KEY",
        regex: r"FLWSECK_TEST-(?i)[a-h0-9]{32}-X",
        secret_group: 0,
        keywords: &[
            r"flwseck_test",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"flyio-access-token",
        ty: r"FLYIO_ACCESS_TOKEN",
        regex: r#"(?-u:\b)((?:fo1_[0-9A-Za-z_-]{43}|fm1[ar]_[a-zA-Z0-9+\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\/]{100,}={0,3}))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"fo1_",
            r"fm1",
            r"fm2_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"frameio-api-token",
        ty: r"FRAMEIO_API_TOKEN",
        regex: r"fio-u-(?i)[a-z0-9\-_=]{64}",
        secret_group: 0,
        keywords: &[
            r"fio-u-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"freshbooks-access-token",
        ty: r"FRESHBOOKS_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:freshbooks)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"freshbooks",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gcp-api-key",
        ty: r"GCP_API_KEY",
        regex: r#"(?-u:\b)(AIza[0-9A-Za-z_-]{35})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"aiza",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: false,
                regexes: &[
                    r"AIzaSyabcdefghijklmnopqrstuvwxyz1234567",
                    r"AIzaSyAnLA7NfeLquW1tJFpx_eQCxoX-oo6YyIs",
                    r"AIzaSyCkEhVjf3pduRDt6d1yKOMitrUEke8agEM",
                    r"AIzaSyDMAScliyLx7F0NPDEJi1QmyCgHIAODrlU",
                    r"AIzaSyD3asb-2pEZVqMkmL6M9N6nHZRR_znhrh0",
                    r"AIzayDNSXIbFmlXbIE6mCzDLQAqITYefhixbX4A",
                    r"AIzaSyAdOS2zB6NCsk1pCdZ4-P6GBdi_UUPwX7c",
                    r"AIzaSyASWm6HmTMdYWpgMnjRBjxcQ9CKctWmLd4",
                    r"AIzaSyANUvH9H9BsUccjsu2pCmEkOPjjaXeDQgY",
                    r"AIzaSyA5_iVawFQ8ABuTZNUdcwERLJv_a_p4wtM",
                    r"AIzaSyA4UrcGxgwQFTfaI3no3t7Lt1sjmdnP5sQ",
                    r"AIzaSyDSb51JiIcB6OJpwwMicseKRhhrOq1cS7g",
                    r"AIzaSyBF2RrAIm4a0mO64EShQfqfd2AFnzAvvuU",
                    r"AIzaSyBcE-OOIbhjyR83gm4r2MFCu4MJmprNXsw",
                    r"AIzaSyB8qGxt4ec15vitgn44duC5ucxaOi4FmqE",
                    r"AIzaSyA8vmApnrHNFE0bApF4hoZ11srVL_n0nvY",
                ],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"github-app-token",
        ty: r"GITHUB_APP_TOKEN",
        regex: r"(?:ghu|ghs)_[0-9a-zA-Z]{36}",
        secret_group: 0,
        keywords: &[
            r"ghu_",
            r"ghs_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: true,
                regexes: &[],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"github-fine-grained-pat",
        ty: r"GITHUB_FINE_GRAINED_PAT",
        regex: r"github_pat_[0-9A-Za-z_]{82}",
        secret_group: 0,
        keywords: &[
            r"github_pat_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"github-oauth",
        ty: r"GITHUB_OAUTH",
        regex: r"gho_[0-9a-zA-Z]{36}",
        secret_group: 0,
        keywords: &[
            r"gho_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"github-pat",
        ty: r"GITHUB_PAT",
        regex: r"ghp_[0-9a-zA-Z]{36}",
        secret_group: 0,
        keywords: &[
            r"ghp_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: true,
                regexes: &[],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"github-refresh-token",
        ty: r"GITHUB_REFRESH_TOKEN",
        regex: r"ghr_[0-9a-zA-Z]{36}",
        secret_group: 0,
        keywords: &[
            r"ghr_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-cicd-job-token",
        ty: r"GITLAB_CICD_JOB_TOKEN",
        regex: r"glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}",
        secret_group: 0,
        keywords: &[
            r"glcbt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-deploy-token",
        ty: r"GITLAB_DEPLOY_TOKEN",
        regex: r"gldt-[0-9a-zA-Z_\-]{20}",
        secret_group: 0,
        keywords: &[
            r"gldt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-feed-token",
        ty: r"GITLAB_FEED_TOKEN",
        regex: r"glft-[0-9a-zA-Z_\-]{20}",
        secret_group: 0,
        keywords: &[
            r"glft-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-incoming-mail-token",
        ty: r"GITLAB_INCOMING_MAIL_TOKEN",
        regex: r"glimt-[0-9a-zA-Z_\-]{25}",
        secret_group: 0,
        keywords: &[
            r"glimt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-kubernetes-agent-token",
        ty: r"GITLAB_KUBERNETES_AGENT_TOKEN",
        regex: r"glagent-[0-9a-zA-Z_\-]{50}",
        secret_group: 0,
        keywords: &[
            r"glagent-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-oauth-app-secret",
        ty: r"GITLAB_OAUTH_APP_SECRET",
        regex: r"gloas-[0-9a-zA-Z_\-]{64}",
        secret_group: 0,
        keywords: &[
            r"gloas-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-pat",
        ty: r"GITLAB_PAT",
        regex: r"glpat-[0-9A-Za-z_-]{20}",
        secret_group: 0,
        keywords: &[
            r"glpat-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-pat-routable",
        ty: r"GITLAB_PAT_ROUTABLE",
        regex: r"(?-u:\b)glpat-[0-9a-zA-Z_-]{27,300}\.[0-9a-z]{2}[0-9a-z]{7}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"glpat-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-ptt",
        ty: r"GITLAB_PTT",
        regex: r"glptt-[0-9a-f]{40}",
        secret_group: 0,
        keywords: &[
            r"glptt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-rrt",
        ty: r"GITLAB_RRT",
        regex: r"GR1348941[0-9A-Za-z_-]{20}",
        secret_group: 0,
        keywords: &[
            r"gr1348941",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-runner-authentication-token",
        ty: r"GITLAB_RUNNER_AUTHENTICATION_TOKEN",
        regex: r"glrt-[0-9a-zA-Z_\-]{20}",
        secret_group: 0,
        keywords: &[
            r"glrt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-runner-authentication-token-routable",
        ty: r"GITLAB_RUNNER_AUTHENTICATION_TOKEN_ROUTABLE",
        regex: r"(?-u:\b)glrt-t[0-9]_[0-9a-zA-Z_\-]{27,300}\.[0-9a-z]{2}[0-9a-z]{7}(?-u:\b)",
        secret_group: 0,
        keywords: &[
            r"glrt-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-scim-token",
        ty: r"GITLAB_SCIM_TOKEN",
        regex: r"glsoat-[0-9a-zA-Z_\-]{20}",
        secret_group: 0,
        keywords: &[
            r"glsoat-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitlab-session-cookie",
        ty: r"GITLAB_SESSION_COOKIE",
        regex: r"_gitlab_session=[0-9a-z]{32}",
        secret_group: 0,
        keywords: &[
            r"_gitlab_session=",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gitter-access-token",
        ty: r"GITTER_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:gitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9_-]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"gitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"gocardless-api-token",
        ty: r"GOCARDLESS_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:gocardless)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(live_(?i)[a-z0-9\-_=]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"live_",
            r"gocardless",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"grafana-api-key",
        ty: r"GRAFANA_API_KEY",
        regex: r#"(?i)(?-u:\b)(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"eyjrijoi",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"grafana-cloud-api-token",
        ty: r"GRAFANA_CLOUD_API_TOKEN",
        regex: r#"(?i)(?-u:\b)(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"glc_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"grafana-service-account-token",
        ty: r"GRAFANA_SERVICE_ACCOUNT_TOKEN",
        regex: r#"(?i)(?-u:\b)(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"glsa_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"harness-api-key",
        ty: r"HARNESS_API_KEY",
        regex: r"(?:pat|sat)\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9]{24}\.[a-zA-Z0-9]{20}",
        secret_group: 0,
        keywords: &[
            r"pat.",
            r"sat.",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"hashicorp-tf-api-token",
        ty: r"HASHICORP_TF_API_TOKEN",
        regex: r"(?i)[a-z0-9]{14}\.(?-i:atlasv1)\.[a-z0-9\-_=]{60,70}",
        secret_group: 0,
        keywords: &[
            r"atlasv1",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[],
    },
    Rule {
        id: r"heroku-api-key",
        ty: r"HEROKU_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:heroku)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"heroku",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"heroku-api-key-v2",
        ty: r"HEROKU_API_KEY_V2",
        regex: r#"(?-u:\b)((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"hrku-aa",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"hubspot-api-key",
        ty: r"HUBSPOT_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:hubspot)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"hubspot",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"huggingface-access-token",
        ty: r"HUGGINGFACE_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(hf_(?i:[a-z]{34}))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"hf_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"huggingface-organization-api-token",
        ty: r"HUGGINGFACE_ORGANIZATION_API_TOKEN",
        regex: r#"(?-u:\b)(api_org_(?i:[a-z]{34}))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"api_org_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"infracost-api-token",
        ty: r"INFRACOST_API_TOKEN",
        regex: r#"(?-u:\b)(ico-[a-zA-Z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"ico-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"intercom-api-key",
        ty: r"INTERCOM_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:intercom)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{60})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"intercom",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"intra42-client-secret",
        ty: r"INTRA42_CLIENT_SECRET",
        regex: r#"(?-u:\b)(s-s4t2(?:ud|af)-(?i)[abcdef0123456789]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"intra",
            r"s-s4t2ud-",
            r"s-s4t2af-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"jfrog-api-key",
        ty: r"JFROG_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{73})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"jfrog",
            r"artifactory",
            r"bintray",
            r"xray",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"jfrog-identity-token",
        ty: r"JFROG_IDENTITY_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"jfrog",
            r"artifactory",
            r"bintray",
            r"xray",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"jwt",
        ty: r"JWT",
        regex: r#"(?-u:\b)(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"ey",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"jwt-base64",
        ty: r"JWT_BASE64",
        regex: r"(?-u:\b)ZXlK(?:(?P<alg>aGJHY2lPaU)|(?P<apu>aGNIVWlPaU)|(?P<apv>aGNIWWlPaU)|(?P<aud>aGRXUWlPaU)|(?P<b64>aU5qUWlP)|(?P<crit>amNtbDBJanBi)|(?P<cty>amRIa2lPaU)|(?P<epk>bGNHc2lPbn)|(?P<enc>bGJtTWlPaU)|(?P<jku>cWEzVWlPaU)|(?P<jwk>cWQyc2lPb)|(?P<iss>cGMzTWlPaU)|(?P<iv>cGRpSTZJ)|(?P<kid>cmFXUWlP)|(?P<key_ops>clpYbGZiM0J6SWpwY)|(?P<kty>cmRIa2lPaUp)|(?P<nonce>dWIyNWpaU0k2)|(?P<p2c>d01tTWlP)|(?P<p2s>d01uTWlPaU)|(?P<ppt>d2NIUWlPaU)|(?P<sub>emRXSWlPaU)|(?P<svt>emRuUWlP)|(?P<tag>MFlXY2lPaU)|(?P<typ>MGVYQWlPaUp)|(?P<url>MWNtd2l)|(?P<use>MWMyVWlPaUp)|(?P<ver>MlpYSWlPaU)|(?P<version>MlpYSnphVzl1SWpv)|(?P<x>NElqb2)|(?P<x5c>NE5XTWlP)|(?P<x5t>NE5YUWlPaU)|(?P<x5ts256>NE5YUWpVekkxTmlJNkl)|(?P<x5u>NE5YVWlPaU)|(?P<zip>NmFYQWlPaU))[a-zA-Z0-9\/\\_+\-\r\n]{40,}={0,2}",
        secret_group: 0,
        keywords: &[
            r"zxlk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"kraken-access-token",
        ty: r"KRAKEN_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:kraken)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9\/=_\+\-]{80,90})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"kraken",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"kucoin-access-token",
        ty: r"KUCOIN_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:kucoin)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{24})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"kucoin",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"kucoin-secret-key",
        ty: r"KUCOIN_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:kucoin)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"kucoin",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"launchdarkly-access-token",
        ty: r"LAUNCHDARKLY_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:launchdarkly)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"launchdarkly",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"linear-api-key",
        ty: r"LINEAR_API_KEY",
        regex: r"lin_api_(?i)[a-z0-9]{40}",
        secret_group: 0,
        keywords: &[
            r"lin_api_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"linear-client-secret",
        ty: r"LINEAR_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:linear)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"linear",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"linkedin-client-secret",
        ty: r"LINKEDIN_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:linked[_-]?in)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"linkedin",
            r"linked_in",
            r"linked-in",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"lob-api-key",
        ty: r"LOB_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:lob)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}((live|test)_[a-f0-9]{35})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"test_",
            r"live_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"looker-client-secret",
        ty: r"LOOKER_CLIENT_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:looker)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{24})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"looker",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"mailchimp-api-key",
        ty: r"MAILCHIMP_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:MailchimpSDK.initialize|mailchimp)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{32}-us[0-9][0-9])(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"mailchimp",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"mailgun-private-api-token",
        ty: r"MAILGUN_PRIVATE_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:mailgun)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(key-[a-f0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"mailgun",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"mailgun-signing-key",
        ty: r"MAILGUN_SIGNING_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:mailgun)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"mailgun",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"mapbox-api-token",
        ty: r"MAPBOX_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:mapbox)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(pk\.[a-z0-9]{60}\.[a-z0-9]{22})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"mapbox",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"mattermost-access-token",
        ty: r"MATTERMOST_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:mattermost)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{26})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"mattermost",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"maxmind-license-key",
        ty: r"MAXMIND_LICENSE_KEY",
        regex: r#"(?-u:\b)([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"_mmk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"messagebird-api-token",
        ty: r"MESSAGEBIRD_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:message[_-]?bird)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{25})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"messagebird",
            r"message-bird",
            r"message_bird",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"microsoft-teams-webhook",
        ty: r"MICROSOFT_TEAMS_WEBHOOK",
        regex: r"https://[a-z0-9]+\.webhook\.office\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}",
        secret_group: 0,
        keywords: &[
            r"webhook.office.com",
            r"webhookb2",
            r"incomingwebhook",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"netlify-access-token",
        ty: r"NETLIFY_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:netlify)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{40,46})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"netlify",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"new-relic-insert-key",
        ty: r"NEW_RELIC_INSERT_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(NRII-[a-z0-9-]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"nrii-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"new-relic-user-api-key",
        ty: r"NEW_RELIC_USER_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(NRAK-[a-z0-9]{27})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"nrak",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"notion-api-token",
        ty: r"NOTION_API_TOKEN",
        regex: r#"(?-u:\b)(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"ntn_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"npm-access-token",
        ty: r"NPM_ACCESS_TOKEN",
        regex: r#"(?i)(?-u:\b)(npm_[a-z0-9]{36})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"npm_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"nytimes-access-token",
        ty: r"NYTIMES_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:nytimes|new-york-times,|newyorktimes)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9=_\-]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"nytimes",
            r"new-york-times",
            r"newyorktimes",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"octopus-deploy-api-key",
        ty: r"OCTOPUS_DEPLOY_API_KEY",
        regex: r#"(?-u:\b)(API-[A-Z0-9]{26})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"api-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"okta-access-token",
        ty: r"OKTA_ACCESS_TOKEN",
        regex: r#"[0-9A-Za-z_.-]{0,50}?(?i:[0-9A-Za-z_.-]{0,50}?(?:(?-i:[Oo]kta|OKTA))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(00[0-9A-Za-z_=\-]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"okta",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"openai-api-key",
        ty: r"OPENAI_API_KEY",
        regex: r#"(?-u:\b)(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})(?-u:\b)|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"t3blbkfj",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"openshift-user-token",
        ty: r"OPENSHIFT_USER_TOKEN",
        regex: r"(?-u:\b)(sha256~[0-9A-Za-z_-]{43})(?:[^0-9A-Za-z_-]|\z)",
        secret_group: 0,
        keywords: &[
            r"sha256~",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[],
    },
    Rule {
        id: r"perplexity-api-key",
        ty: r"PERPLEXITY_API_KEY",
        regex: r#"(?-u:\b)(pplx-[a-zA-Z0-9]{48})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$|(?-u:\b))"#,
        secret_group: 0,
        keywords: &[
            r"pplx-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"plaid-api-token",
        ty: r"PLAID_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:plaid)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"plaid",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"plaid-secret-key",
        ty: r"PLAID_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:plaid)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{30})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"plaid",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[],
    },
    Rule {
        id: r"planetscale-api-token",
        ty: r"PLANETSCALE_API_TOKEN",
        regex: r#"(?-u:\b)(pscale_tkn_(?i)[0-9A-Za-z_=\.-]{32,64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pscale_tkn_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"planetscale-oauth-token",
        ty: r"PLANETSCALE_OAUTH_TOKEN",
        regex: r#"(?-u:\b)(pscale_oauth_[0-9A-Za-z_=\.-]{32,64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pscale_oauth_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"planetscale-password",
        ty: r"PLANETSCALE_PASSWORD",
        regex: r#"(?i)(?-u:\b)(pscale_pw_(?i)[0-9A-Za-z_=\.-]{32,64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pscale_pw_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"postman-api-token",
        ty: r"POSTMAN_API_TOKEN",
        regex: r#"(?-u:\b)(PMAK-(?i)[a-f0-9]{24}\-[a-f0-9]{34})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pmak-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"prefect-api-token",
        ty: r"PREFECT_API_TOKEN",
        regex: r#"(?-u:\b)(pnu_[a-zA-Z0-9]{36})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pnu_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"private-key",
        ty: r"PRIVATE_KEY",
        regex: r"(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\t\n\f\r [^\t\n\f\r ]-]{64,}?KEY(?: BLOCK)?-----",
        secret_group: 0,
        keywords: &[
            r"-----begin",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"privateai-api-token",
        ty: r"PRIVATEAI_API_TOKEN",
        regex: r#"[0-9A-Za-z_.-]{0,50}?(?i:[0-9A-Za-z_.-]{0,50}?(?:private[_-]?ai)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3})(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{32})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"privateai",
            r"private_ai",
            r"private-ai",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"pulumi-api-token",
        ty: r"PULUMI_API_TOKEN",
        regex: r#"(?-u:\b)(pul-[a-f0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"pul-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"pypi-upload-token",
        ty: r"PYPI_UPLOAD_TOKEN",
        regex: r"pypi-AgEIcHlwaS5vcmc[0-9A-Za-z_-]{50,1000}",
        secret_group: 0,
        keywords: &[
            r"pypi-ageichlwas5vcmc",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"rapidapi-access-token",
        ty: r"RAPIDAPI_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:rapidapi)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9_-]{50})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"rapidapi",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"readme-api-token",
        ty: r"README_API_TOKEN",
        regex: r#"(?-u:\b)(rdme_[a-z0-9]{70})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"rdme_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"rubygems-api-token",
        ty: r"RUBYGEMS_API_TOKEN",
        regex: r#"(?-u:\b)(rubygems_[a-f0-9]{48})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"rubygems_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"scalingo-api-token",
        ty: r"SCALINGO_API_TOKEN",
        regex: r#"(?-u:\b)(tk-us-[0-9A-Za-z_-]{48})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"tk-us-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sendbird-access-token",
        ty: r"SENDBIRD_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:sendbird)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sendbird",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sendgrid-api-token",
        ty: r"SENDGRID_API_TOKEN",
        regex: r#"(?-u:\b)(SG\.(?i)[a-z0-9=_\-\.]{66})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sg.",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sendinblue-api-token",
        ty: r"SENDINBLUE_API_TOKEN",
        regex: r#"(?-u:\b)(xkeysib-[a-f0-9]{64}\-(?i)[a-z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"xkeysib-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sentry-access-token",
        ty: r"SENTRY_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:sentry)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sentry",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sentry-org-token",
        ty: r"SENTRY_ORG_TOKEN",
        regex: r"(?-u:\b)sntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|\z)",
        secret_group: 0,
        keywords: &[
            r"sntrys_eyjpyxqio",
        ],
        gated: true,
        entropy: 4.5,
        allowlists: &[],
    },
    Rule {
        id: r"sentry-user-token",
        ty: r"SENTRY_USER_TOKEN",
        regex: r#"(?-u:\b)(sntryu_[a-f0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sntryu_",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[],
    },
    Rule {
        id: r"settlemint-application-access-token",
        ty: r"SETTLEMINT_APPLICATION_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(sm_aat_[a-zA-Z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sm_aat",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"settlemint-personal-access-token",
        ty: r"SETTLEMINT_PERSONAL_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(sm_pat_[a-zA-Z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sm_pat",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"settlemint-service-access-token",
        ty: r"SETTLEMINT_SERVICE_ACCESS_TOKEN",
        regex: r#"(?-u:\b)(sm_sat_[a-zA-Z0-9]{16})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sm_sat",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"shippo-api-token",
        ty: r"SHIPPO_API_TOKEN",
        regex: r#"(?-u:\b)(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"shippo_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"shopify-access-token",
        ty: r"SHOPIFY_ACCESS_TOKEN",
        regex: r"shpat_[a-fA-F0-9]{32}",
        secret_group: 0,
        keywords: &[
            r"shpat_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"shopify-custom-access-token",
        ty: r"SHOPIFY_CUSTOM_ACCESS_TOKEN",
        regex: r"shpca_[a-fA-F0-9]{32}",
        secret_group: 0,
        keywords: &[
            r"shpca_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"shopify-private-app-access-token",
        ty: r"SHOPIFY_PRIVATE_APP_ACCESS_TOKEN",
        regex: r"shppa_[a-fA-F0-9]{32}",
        secret_group: 0,
        keywords: &[
            r"shppa_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"shopify-shared-secret",
        ty: r"SHOPIFY_SHARED_SECRET",
        regex: r"shpss_[a-fA-F0-9]{32}",
        secret_group: 0,
        keywords: &[
            r"shpss_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sidekiq-secret",
        ty: r"SIDEKIQ_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"bundle_enterprise__contribsys__com",
            r"bundle_gems__contribsys__com",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sidekiq-sensitive-url",
        ty: r"SIDEKIQ_SENSITIVE_URL",
        regex: r"(?i)(?-u:\b)https?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\/|\#|\?|:]|$)",
        secret_group: 0,
        keywords: &[
            r"gems.contribsys.com",
            r"enterprise.contribsys.com",
        ],
        gated: false,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-app-token",
        ty: r"SLACK_APP_TOKEN",
        regex: r"(?i)xapp-[0-9]-[A-Z0-9]+-[0-9]+-[a-z0-9]+",
        secret_group: 0,
        keywords: &[
            r"xapp",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-bot-token",
        ty: r"SLACK_BOT_TOKEN",
        regex: r"xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*",
        secret_group: 0,
        keywords: &[
            r"xoxb",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-config-access-token",
        ty: r"SLACK_CONFIG_ACCESS_TOKEN",
        regex: r"(?i)xoxe.xox[bp]-[0-9]-[A-Z0-9]{163,166}",
        secret_group: 0,
        keywords: &[
            r"xoxe.xoxb-",
            r"xoxe.xoxp-",
        ],
        gated: false,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-config-refresh-token",
        ty: r"SLACK_CONFIG_REFRESH_TOKEN",
        regex: r"(?i)xoxe-[0-9]-[A-Z0-9]{146}",
        secret_group: 0,
        keywords: &[
            r"xoxe-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-legacy-bot-token",
        ty: r"SLACK_LEGACY_BOT_TOKEN",
        regex: r"xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}",
        secret_group: 0,
        keywords: &[
            r"xoxb",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-legacy-token",
        ty: r"SLACK_LEGACY_TOKEN",
        regex: r"xox[os]-[0-9]+-[0-9]+-[0-9]+-[a-fA-F0-9]+",
        secret_group: 0,
        keywords: &[
            r"xoxo",
            r"xoxs",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-legacy-workspace-token",
        ty: r"SLACK_LEGACY_WORKSPACE_TOKEN",
        regex: r"xox[ar]-(?:[0-9]-)?[0-9a-zA-Z]{8,48}",
        secret_group: 0,
        keywords: &[
            r"xoxa",
            r"xoxr",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-user-token",
        ty: r"SLACK_USER_TOKEN",
        regex: r"xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}",
        secret_group: 0,
        keywords: &[
            r"xoxp-",
            r"xoxe-",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"slack-webhook-url",
        ty: r"SLACK_WEBHOOK_URL",
        regex: r"(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}",
        secret_group: 0,
        keywords: &[
            r"hooks.slack.com",
        ],
        gated: false,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"snyk-api-token",
        ty: r"SNYK_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"snyk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sonar-api-token",
        ty: r"SONAR_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\-]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 2,
        keywords: &[
            r"sonar",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sourcegraph-access-token",
        ty: r"SOURCEGRAPH_ACCESS_TOKEN",
        regex: r#"(?i)(?-u:\b)((?-u:\b)(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})(?-u:\b))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sgp_",
            r"sourcegraph",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"square-access-token",
        ty: r"SQUARE_ACCESS_TOKEN",
        regex: r#"(?-u:\b)((?:EAAA|sq0atp-)[0-9A-Za-z_-]{22,60})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sq0atp-",
            r"eaaa",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"squarespace-access-token",
        ty: r"SQUARESPACE_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:squarespace)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"squarespace",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"stripe-access-token",
        ty: r"STRIPE_ACCESS_TOKEN",
        regex: r#"(?-u:\b)((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sk_test",
            r"sk_live",
            r"sk_prod",
            r"rk_test",
            r"rk_live",
            r"rk_prod",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"sumologic-access-token",
        ty: r"SUMOLOGIC_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{64})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"sumo",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"telegram-bot-api-token",
        ty: r"TELEGRAM_BOT_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:telegr)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9]{5,16}:(?-i:A)[a-z0-9_\-]{34})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"telegr",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"travisci-access-token",
        ty: r"TRAVISCI_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:travis)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{22})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"travis",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twilio-api-key",
        ty: r"TWILIO_API_KEY",
        regex: r"SK[0-9a-fA-F]{32}",
        secret_group: 0,
        keywords: &[
            r"sk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitch-api-token",
        ty: r"TWITCH_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitch)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{30})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitch",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitter-access-secret",
        ty: r"TWITTER_ACCESS_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{45})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitter-access-token",
        ty: r"TWITTER_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitter-api-key",
        ty: r"TWITTER_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{25})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitter-api-secret",
        ty: r"TWITTER_API_SECRET",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{50})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"twitter-bearer-token",
        ty: r"TWITTER_BEARER_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:twitter)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"twitter",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"typeform-api-token",
        ty: r"TYPEFORM_API_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:typeform)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(tfp_[a-z0-9\-_\.=]{59})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"tfp_",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"vault-batch-token",
        ty: r"VAULT_BATCH_TOKEN",
        regex: r#"(?-u:\b)(hvb\.[0-9A-Za-z_-]{138,300})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"hvb.",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"vault-service-token",
        ty: r"VAULT_SERVICE_TOKEN",
        regex: r#"(?-u:\b)((?:hvs\.[0-9A-Za-z_-]{90,120}|s\.(?i:[a-z0-9]{24})))(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"hvs.",
            r"s.",
        ],
        gated: true,
        entropy: 3.5,
        allowlists: &[
            Allowlist {
                all: false,
                path_or_commit: false,
                regexes: &[
                    r"s\.[A-Za-z]{24}",
                ],
                stopwords: &[],
            },
        ],
    },
    Rule {
        id: r"yandex-access-token",
        ty: r"YANDEX_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:yandex)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(t1\.[A-Z0-9a-z_-]+[=]{0,2}\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"yandex",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"yandex-api-key",
        ty: r"YANDEX_API_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:yandex)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(AQVN[A-Za-z0-9_\-]{35,38})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"yandex",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"yandex-aws-access-token",
        ty: r"YANDEX_AWS_ACCESS_TOKEN",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:yandex)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}(YC[a-zA-Z0-9_\-]{38})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"yandex",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
    Rule {
        id: r"zendesk-secret-key",
        ty: r"ZENDESK_SECRET_KEY",
        regex: r#"(?i)[0-9A-Za-z_.-]{0,50}?(?:zendesk)(?:[ \t0-9A-Za-z_.-]{0,20})[\t\n\f\r '"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\t\n\f\r =]{0,5}([a-z0-9]{40})(?:[\x60'"\t\n\f\r ;]|\\[nr]|$)"#,
        secret_group: 0,
        keywords: &[
            r"zendesk",
        ],
        gated: true,
        entropy: 0.0,
        allowlists: &[],
    },
];

/// Upstream global allowlist regexes, checked against every secret.
pub(crate) const GLOBAL_REGEXES: &[&str] = &[
    r"(?i)^true|false|null$",
    r"^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\*+|\.+)$",
    r"^\$(?:[0-9]+|\{[0-9]+})$",
    r"^\$(?:[A-Z_]+|[a-z_]+)$",
    r"^\$\{(?:[A-Z_]+|[a-z_]+)}$",
    r"^\{\{[ \t]*[0-9A-Za-z_ ().|]+[ \t]*}}$",
    r#"^\$\{\{[ \t]*(?:(?:env|github|secrets|vars)(?:\.[A-Za-z][0-9A-Za-z_]+)+[0-9A-Za-z_ "'&./=|]*)[ \t]*}}$"#,
    r"^%(?:[A-Z_]+|[a-z_]+)%$",
    r"^%[+\-# 0]?[bcdeEfFgGoOpqstTUvxX]$",
    r"^\{[0-9]{0,2}}$",
    r"^@(?:[A-Z_]+|[a-z_]+)@$",
    r"^/Users/(?i)[a-z0-9]+/[0-9A-Za-z_ .-/]+$",
    r"^/(?:bin|etc|home|opt|tmp|usr|var)/[0-9A-Za-z_ ./-]+$",
];

/// Upstream global stopwords: a secret containing one is not a finding.
pub(crate) const GLOBAL_STOPWORDS: &[&str] = &[
    r"014df517-39d1-4453-b7b3-9930c563627c",
    r"abcdefghijklmnopqrstuvwxyz",
];

/// Upstream rules left out of the port, with the reason.
#[cfg_attr(not(test), expect(dead_code, reason = "documentation table, read by tests"))]
pub(crate) const EXCLUDED: &[(&str, &str)] = &[
    (r"generic-api-key", r"generic keyword/assignment rule; too many false positives for one-way redaction (the entropy backstop covers opaque tokens)"),
    (r"adobe-client-id", r"OAuth client identifier, not a secret"),
    (r"asana-client-id", r"OAuth client identifier, not a secret"),
    (r"bitbucket-client-id", r"OAuth client identifier, not a secret"),
    (r"discord-client-id", r"OAuth client identifier, not a secret"),
    (r"linkedin-client-id", r"OAuth client identifier, not a secret"),
    (r"looker-client-id", r"OAuth client identifier, not a secret"),
    (r"messagebird-client-id", r"OAuth client identifier, not a secret"),
    (r"plaid-client-id", r"client identifier, not a secret"),
    (r"new-relic-user-api-id", r"account identifier, not a secret"),
    (r"sumologic-access-id", r"access identifier (paired with a secret that has its own rule)"),
    (r"sendbird-access-id", r"application identifier, not a secret"),
    (r"flutterwave-public-key", r"public key, designed to be embedded in clients"),
    (r"lob-pub-api-key", r"publishable key, designed to be embedded in clients"),
    (r"mailgun-pub-key", r"public validation key, designed to be embedded in clients"),
    (r"new-relic-browser-api-token", r"browser ingest key, embedded in public web pages"),
    (r"gitlab-feature-flag-client-token", r"client-side feature-flag token, embedded in clients"),
    (r"freemius-secret-key", r"gitleaks applies it only to *.php paths"),
    (r"hashicorp-tf-password", r"gitleaks applies it only to *.tf/*.hcl paths"),
    (r"kubernetes-secret-yaml", r"gitleaks applies it only to *.yaml paths"),
    (r"nuget-config-password", r"gitleaks applies it only to nuget.config paths"),
    (r"pkcs12-file", r"path-only rule (matches file names, has no content regex)"),
];
